[package]
name = "LastCard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
[target.'cfg(windows)'.dependencies]
winapi-util = "0.1"
enable-ansi-support = "0.2.1"
